import { Link } from 'react-router-dom'
import { ArrowRight } from 'lucide-react'
import { courses, testimonials, resources, pricing } from '../data/content'
import { Button, CTASection, Reveal, SectionLabel } from '../components/UI'

export default function Home(){return <>
<section className="container-site py-12 lg:py-20"><div className="grid gap-10 lg:grid-cols-12 lg:items-stretch">
  <Reveal className="flex flex-col justify-between lg:col-span-7"><div><p className="eyebrow mb-7">Private French Tutoring — Manila & Online</p><h1 className="display-xl max-w-5xl">French, taught <span className="italic text-cobalt">with clarity.</span></h1></div><div className="mt-10 max-w-xl"><p className="body-lg text-muted">Private French lessons and focused TEF, TCF, and DELF preparation for students who want to communicate with confidence.</p><div className="mt-7 flex flex-wrap gap-3"><Button to="/book">Book a Class</Button><Button to="/courses" variant="outline">Explore Courses</Button></div></div></Reveal>
  <Reveal className="lg:col-span-5"><img src={`${import.meta.env.BASE_URL}images/tutor-hero.webp`} alt="French tutor" fetchPriority="high" decoding="async" className="h-[540px] w-full object-cover grayscale-[10%] lg:h-full"/></Reveal>
</div><div className="mt-10 grid border-y border-line sm:grid-cols-3">{['Private Lessons','Exam Preparation','Online Sessions'].map((x,i)=><div key={x} className="flex gap-4 border-b border-line py-4 sm:border-b-0 sm:border-r sm:px-5 first:pl-0 last:border-r-0"><span className="text-xs text-cobalt">0{i+1}</span><span className="text-xs font-semibold uppercase tracking-[.12em]">{x}</span></div>)}</div></section>

<section className="container-site py-20 lg:py-28"><Reveal><SectionLabel n="01">A clearer way to learn</SectionLabel><h2 className="display-lg max-w-6xl">Learn the language. Understand the structure. <span className="italic">Speak with confidence.</span></h2><p className="mt-8 max-w-xl body-lg text-muted">Lessons are designed to make French feel understandable, practical, and useful—not like a list of rules to memorize.</p></Reveal></section>

<section className="container-site pb-24"><SectionLabel n="02">Courses</SectionLabel><div>{courses.map(c=><Link key={c.name} to={`/courses/${c.slug}`} className="group grid gap-4 border-b border-line py-7 md:grid-cols-12 md:items-center"><span className="text-xs text-cobalt md:col-span-1">{c.id}</span><div className="md:col-span-5"><h3 className="font-display text-4xl transition-transform group-hover:translate-x-2">{c.name}</h3><p className="mt-1 text-sm text-muted">{c.desc}</p></div><span className="text-sm md:col-span-2">{c.level}</span><span className="text-sm md:col-span-2">{c.duration} · {c.price}</span><ArrowRight className="transition-transform group-hover:translate-x-2 md:col-span-2 md:justify-self-end"/></Link>)}</div></section>

<section className="bg-navy text-white"><div className="container-site py-20 lg:py-28"><SectionLabel n="03">Exam Preparation</SectionLabel><div className="grid gap-12 lg:grid-cols-3">{[['TEF','For immigration, work, and academic goals.'],['TCF','Structured preparation for language certification and immigration pathways.'],['DELF','Build the skills and confidence required for official French proficiency certification.']].map(([t,d])=><div key={t} className="border-t border-white/25 pt-5"><div className="font-display text-[7rem] leading-none text-white/15">{t}</div><h3 className="-mt-7 font-display text-4xl">{t} Preparation</h3><p className="mt-4 max-w-sm text-sm leading-6 text-white/65">{d}</p></div>)}</div><div className="mt-12"><Button to="/exam-preparation" variant="light">View Exam Preparation</Button></div></div></section>

<section className="container-site py-24 lg:py-32"><div className="grid gap-12 lg:grid-cols-12 lg:items-center"><Reveal className="lg:col-span-5"><img src={`${import.meta.env.BASE_URL}images/tutor-portrait.webp`} alt="Tutor portrait" loading="lazy" decoding="async" className="aspect-[4/5] w-full object-cover"/></Reveal><Reveal className="lg:col-span-6 lg:col-start-7"><p className="eyebrow mb-5">The Tutor</p><h2 className="display-md">Personalized lessons, built around the way you learn.</h2><p className="mt-7 body-lg text-muted">Clear explanations, thoughtful correction, and practical exercises make each session feel focused and useful. Every lesson adapts to your level, goals, pace, and real-life reasons for learning French.</p><Link to="/about" className="link-line mt-7 text-xs font-semibold uppercase tracking-[.14em]">Meet your tutor <ArrowRight size={15}/></Link></Reveal></div></section>

<section className="container-site pb-24"><SectionLabel n="04">How lessons work</SectionLabel><div className="grid md:grid-cols-4">{['Choose a course','Select a schedule','Join your session','Keep progressing'].map((x,i)=><div className="border-t border-line py-6 md:border-r md:px-5 first:pl-0 last:border-r-0" key={x}><span className="text-xs text-cobalt">0{i+1}</span><h3 className="mt-12 font-display text-3xl">{x}</h3></div>)}</div></section>

<section className="bg-white"><div className="container-site py-24"><SectionLabel n="05">Pricing</SectionLabel><div className="grid gap-px bg-line lg:grid-cols-3">{pricing.map(p=><div key={p.name} className="bg-white p-7"><p className="eyebrow">{p.name}</p><div className="my-7 font-display text-5xl">{p.price}</div><p className="text-sm text-muted">{p.note}</p><div className="mt-9 border-t border-line pt-5 text-sm">{p.lessons}<br/>{p.duration}</div></div>)}</div><Link className="link-line mt-8 text-xs font-semibold uppercase tracking-[.14em]" to="/pricing">See all pricing <ArrowRight size={15}/></Link></div></section>

<section className="container-site py-24"><SectionLabel n="06">Student Notes</SectionLabel><Reveal><blockquote className="max-w-6xl font-display text-[clamp(3rem,5.2vw,6rem)] leading-[.98]">“{testimonials[0].quote}”</blockquote><div className="mt-7 text-xs font-semibold uppercase tracking-[.13em]">{testimonials[0].name} — <span className="text-muted">{testimonials[0].label}</span></div></Reveal></section>

<section className="container-site pb-24"><SectionLabel n="07">Resources</SectionLabel><div className="grid gap-8 lg:grid-cols-3">{resources.slice(0,3).map((r,i)=><Link to={`/resources/${r.slug}`} key={r.title} className={i===0?'lg:col-span-2':''}><div className="overflow-hidden"><img src={r.image} loading="lazy" decoding="async" className={`w-full object-cover transition-transform duration-500 hover:scale-[1.02] ${i===0?'h-[420px]':'h-[300px]'}`} alt=""/></div><p className="eyebrow mt-4">{r.category} · {r.date}</p><h3 className="mt-2 font-display text-3xl">{r.title}</h3></Link>)}</div></section>
<CTASection/></>}
